### PR TITLE
Enable media streaming

### PR DESCRIPTION
**Pull request by alanmcgovern**

### CODE REVIEW

**Comment by alanmcgovern** [comment]
Should address  https://github.com/alanmcgovern/monotorrent/issues/257 well enough for now

**Comment by alanmcgovern** [comment]
@OneFingerCodingWarrior I've (hopefully) simplified things and am in a place where I'm comfortable shipping this in the next release!

I would love it if you could give this new API a shot and let me know if it works well for you. If you have any suggestions to make it easier to work with let me know! If it fails miserably then I really want to know what went wrong :p

**Comment by alanmcgovern** [comment]
@ilyalatt @uponatime2019 Can you take a read my previous comment on this PR. If would be great if you could test things and let me know how you get on. I'd love to release this as long as there are no show-stopper issues! I won't make breaking changes to this API until i release a 'MonoTorrent 2.0.0' :)

**Comment by OneFingerCodingWarrior** [comment]
Well , I will try the new API soon or later.
In fact I also implemented a simple http media streaming function using wcf, but because my code style (well ,you have met it ^_^) and dependency of WCF conflict with MonoTorrent, and unfamiliar with git, so I didn't push the changes. But  I am pretty happy to switch to your new API, and thanks for all the work you have done,

**Comment by alanmcgovern** [comment]
> In fact I also implemented a simple http media streaming function using wcf

My hope is that anyone who wants to expose the data in a custom service/whatever can simply call StreamProvider.CreateStream and then read any data they need from that! They will be able to seek that stream and read data from it and MonoTorrent will magically ensure that data is prioritised/downloaded!

**Comment by alanmcgovern** [comment]
I went ahead and merged this! I'll test it over the next few days before issuing a release with this! There is a small chance I'll make some tweaks between now and then, but i'd say it's unlikely :)

**Pull request merged**
