### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by borigas**
Here's the integration tests I previously copy/pasted on #560. I also added more to show the issue with implicit vs explicit hash check in #565. Let me know if I'm misunderstanding the intended behavior of `StartAsync()`

### CODE REVIEW

**Comment by borigas** [comment]
I think the failures all boil down to the empty file only being created by the explicit hash check:
image

**Comment by borigas** [comment]
Did you mean to close this when merging `more-fixes-for-empty-files`? If these tests aren't helpful, I'm ok with that. Just a little confused.

On the plus side, they're all green with the latest changes
image

**Comment by alanmcgovern** [comment]
Oh weird, I think that was github auto-closing tickets, though i don't know why this one was auto-closed. It'd be great if you could re-open the PR - the 'reopen' button is disabled for me, probably because the PR originated from a fork!

**Comment by alanmcgovern** [comment]
ah! it auto closed as you were targetting the `more-fixes-for-empty-files` branch and that's been deleted. That probably explains why i can't reopen this PR too :)

**Comment by borigas** [comment]
Reopened in #567

**Pull request closed without merging**
