### PR TITLE
[core] Skip parsing key if value is an empty string

### PR DESCRIPTION
**Pull request by winterqt**
Let me know if you'd like a more descriptive commit message, or if I should add a description like I did in #583.

### CODE REVIEW

**Review by alanmcgovern — APPROVED** [review]
Looks perfect!

**Comment by alanmcgovern** [comment]
Thanks for that, I'll ship a new release shortly :)

**Comment by winterqt** [comment]
Thank you!

**Comment by Qstick** [comment]
Thanks @alanmcgovern, let us know on the release timing and we'll get this bumped up in Radarr.

**Comment by alanmcgovern** [comment]
I'll do it tomorrow, and I'll backport it to the stable branch as well. I assume radarr is still on 2.x :)

**Comment by alanmcgovern** [comment]
@Qstick Done!

https://www.nuget.org/packages/MonoTorrent/2.0.7

**Pull request merged**
